"""Business logic for vector similarity search.

This module is a thin re-export facade. The hybrid retrieval pipeline was
split into focused modules under ``backend/search/`` (reliability, types,
query_variants, bm25, fusion, embedding, retrieval_db, pipeline); this file
keeps the historical ``backend.search.service`` import path working for
every caller and test that imports names from it.

Tests that monkeypatch behaviour (rather than just importing names) must
target the module where the patched name is actually looked up at call
time — see each submodule for its own collaborators.
"""

from __future__ import annotations

from backend.core.config import settings
from backend.core.openai_client import get_async_openai_client
from backend.core.openai_retry import async_call_openai_with_retry
from backend.knowledge.entity_extractor import extract_entities_from_query
from backend.search.bm25 import (
    BM25_CANDIDATE_POOL,
    BM25_DEBUG_VARIANT_TEXT_MAX_LEN,
    _bm25_queries_for_script,
    _bm25_score_candidates_with_signal,
    _format_bm25_trace_results,
    _has_lexical_signal,
    _is_en_query,
    _lexical_overlap_results,
    _normalize_scored_results,
    _prepare_bm25_corpus,
    _resolve_bm25_expansion_mode,
    _run_bm25_search,
    _score_prepared_bm25_corpus,
)
from backend.search.embedding import (
    async_embed_queries,
    async_embed_queries_with_stats,
    async_embed_query,
)
from backend.search.fusion import (
    MMR_LAMBDA,
    SCRIPT_BOOST_FACTOR,
    _candidate_similarity,
    _collect_score_map,
    _sort_scored_embeddings,
    apply_script_boost,
    detect_source_overlaps,
    mmr_select,
    reciprocal_rank_fusion,
)
from backend.search.pipeline import (
    RRF_CANDIDATE_POOL_MULTIPLIER,
    _async_resolve_reranker_strategy,
    _async_run_candidate_stage,
    _async_run_quality_stage,
    _async_run_query_stage,
    _async_run_ranking_stage,
    _build_empty_result_bundle,
    _reranker_strategy_value,
    build_variant_trace_metadata,
    build_variant_trace_tag,
    search_similar_chunks_detailed_async,
)
from backend.search.query_variants import (
    QUERY_REWRITE_HTTP_TIMEOUT_SECONDS,
    _async_rewrite_query_for_retrieval,
    _build_semantic_rewrite_prompt,
    _normalize_query_variants,
    async_semantic_query_rewrite,
    async_semantic_query_rewrite_for_kb,
    detect_query_script_bucket,
    expand_query,
)
from backend.search.reliability import (
    MAX_OVERLAP_CHECK_CANDIDATES,
    AdjudicatedContradiction,
    ContradictionAdjudicationEvidence,
    ContradictionEvidence,
    ContradictionPair,
    ContradictionPolicyEvaluation,
    ReliabilityCapReason,
    ReliabilityEvidence,
    ReliabilityScore,
    ReliabilitySignal,
    ReliabilitySignalKind,
    RetrievalReliability,
    SourceOverlapEvidence,
    SourceOverlapPair,
    _build_contradiction_adjudication_evidence,
    build_reliability_assessment,
    build_reliability_projection,
    default_retrieval_reliability,
    detect_metadata_contradictions,
    serialize_adjudicated_contradiction,
    serialize_contradiction_pair,
    serialize_reliability,
    serialize_source_overlap_pair,
)
from backend.search.retrieval_db import (
    ENTITY_SEARCH_CANDIDATE_LIMIT,
    _async_build_vector_candidate_set,
    _async_pgvector_search,
    _async_python_cosine_search,
    _async_tenant_has_embeddings,
    async_detect_tenant_kb_script,
    async_detect_tenant_kb_scripts,
    async_entity_overlap_search,
    invalidate_tenant_kb_script_cache,
    invalidate_tenant_search_caches,
)
from backend.search.types import (
    BM25ExpansionMode,
    BM25SearchBundle,
    BM25Winner,
    MMRSelectionResult,
    PreparedBM25Corpus,
    SearchResultBundle,
    VariantMode,
    VectorCandidateSet,
    _CandidateStageResult,
    _QualityStageResult,
    _QueryStageResult,
    _RankingStageResult,
)
from backend.utils.math import cosine_similarity

__all__ = [
    "BM25_CANDIDATE_POOL",
    "BM25_DEBUG_VARIANT_TEXT_MAX_LEN",
    "ENTITY_SEARCH_CANDIDATE_LIMIT",
    "MAX_OVERLAP_CHECK_CANDIDATES",
    "MMR_LAMBDA",
    "QUERY_REWRITE_HTTP_TIMEOUT_SECONDS",
    "RRF_CANDIDATE_POOL_MULTIPLIER",
    "SCRIPT_BOOST_FACTOR",
    "AdjudicatedContradiction",
    "BM25ExpansionMode",
    "BM25SearchBundle",
    "BM25Winner",
    "ContradictionAdjudicationEvidence",
    "ContradictionEvidence",
    "ContradictionPair",
    "ContradictionPolicyEvaluation",
    "MMRSelectionResult",
    "PreparedBM25Corpus",
    "ReliabilityCapReason",
    "ReliabilityEvidence",
    "ReliabilityScore",
    "ReliabilitySignal",
    "ReliabilitySignalKind",
    "RetrievalReliability",
    "SearchResultBundle",
    "SourceOverlapEvidence",
    "SourceOverlapPair",
    "VariantMode",
    "VectorCandidateSet",
    "_CandidateStageResult",
    "_QualityStageResult",
    "_QueryStageResult",
    "_RankingStageResult",
    "_async_build_vector_candidate_set",
    "_async_pgvector_search",
    "_async_python_cosine_search",
    "_async_resolve_reranker_strategy",
    "_async_rewrite_query_for_retrieval",
    "_async_run_candidate_stage",
    "_async_run_quality_stage",
    "_async_run_query_stage",
    "_async_run_ranking_stage",
    "_async_tenant_has_embeddings",
    "_bm25_queries_for_script",
    "_bm25_score_candidates_with_signal",
    "_build_contradiction_adjudication_evidence",
    "_build_empty_result_bundle",
    "_build_semantic_rewrite_prompt",
    "_candidate_similarity",
    "_collect_score_map",
    "_format_bm25_trace_results",
    "_has_lexical_signal",
    "_is_en_query",
    "_lexical_overlap_results",
    "_normalize_query_variants",
    "_normalize_scored_results",
    "_prepare_bm25_corpus",
    "_reranker_strategy_value",
    "_resolve_bm25_expansion_mode",
    "_run_bm25_search",
    "_score_prepared_bm25_corpus",
    "_sort_scored_embeddings",
    "apply_script_boost",
    "async_call_openai_with_retry",
    "async_detect_tenant_kb_script",
    "async_detect_tenant_kb_scripts",
    "async_embed_queries",
    "async_embed_queries_with_stats",
    "async_embed_query",
    "async_entity_overlap_search",
    "async_semantic_query_rewrite",
    "async_semantic_query_rewrite_for_kb",
    "build_reliability_assessment",
    "build_reliability_projection",
    "build_variant_trace_metadata",
    "build_variant_trace_tag",
    "cosine_similarity",
    "default_retrieval_reliability",
    "detect_metadata_contradictions",
    "detect_query_script_bucket",
    "detect_source_overlaps",
    "expand_query",
    "extract_entities_from_query",
    "get_async_openai_client",
    "invalidate_tenant_kb_script_cache",
    "invalidate_tenant_search_caches",
    "mmr_select",
    "reciprocal_rank_fusion",
    "search_similar_chunks_detailed_async",
    "serialize_adjudicated_contradiction",
    "serialize_contradiction_pair",
    "serialize_reliability",
    "serialize_source_overlap_pair",
    "settings",
]
