"""init: create users, clients, documents, embeddings, chats, messages tables

Revision ID: b791b570709d
Revises: 3e6c7b506784
Create Date: 2026-03-17 22:36:02.780484

"""
from __future__ import annotations

# revision identifiers, used by Alembic.
revision = 'b791b570709d'
down_revision = '3e6c7b506784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # Intentional fail-loud: downgrade is never executed (see project CLAUDE.md).
    # Keep this as raise, not pass, so accidental `alembic downgrade` errors out
    # instead of silently moving `alembic_version` backward while schema stays.
    raise NotImplementedError("downgrade is not supported for this migration")
