"""init: create users, clients, documents, embeddings, chats, messages tables

Revision ID: b791b570709d
Revises: 3e6c7b506784
Create Date: 2026-03-17 22:36:02.780484

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b791b570709d'
down_revision = '3e6c7b506784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # no-op: downgrade is never executed (see project CLAUDE.md)
    pass
