"""add openai_api_key to clients

Revision ID: c43e952ca145
Revises: b791b570709d
Create Date: 2026-03-18 13:51:37.259263

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43e952ca145'
down_revision = 'b791b570709d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('openai_api_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'openai_api_key')
    # ### end Alembic commands ###

