// Pre-mount UI copy. Kept minimal — once ChatWidget mounts, all user-facing
// text is generated by the LLM in the user's language (see project rule:
// "User-facing strings always localized"). These strings only appear in
// transient states before the widget itself takes over (loading splash,
// misconfig diagnostic). New languages: add an entry to LOCALES with all
// keys filled.

type StringKey = "loading" | "misconfigured_title" | "misconfigured_body";

const LOCALES: Record<string, Record<StringKey, string>> = {
  en: {
    loading: "Loading…",
    misconfigured_title: "Widget misconfigured",
    misconfigured_body: "Missing required loader parameters: botId and apiBase.",
  },
  ru: {
    loading: "Загрузка…",
    misconfigured_title: "Виджет настроен неверно",
    misconfigured_body: "Отсутствуют обязательные параметры loader'а: botId и apiBase.",
  },
};

export function pickLanguage(locale: string | null | undefined): string {
  if (!locale) return "en";
  const primary = locale.toLowerCase().split(/[-_]/)[0];
  return primary in LOCALES ? primary : "en";
}

export function t(locale: string | null | undefined, key: StringKey): string {
  return LOCALES[pickLanguage(locale)][key];
}
